<?php
/**
 * @copyright  Copyright (c) 2012 by  Bootic.
 */
?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Bootic - Manage your products (email: '.Mage::getStoreConfig('bootic/account/email').')') ?></h3></td>
            <td class="a-right">
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getChildHtml('bootic_adminhtml_catalog_tabs'); ?>
<div id="bootic_catalog_tab_content"></div>
